name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt pyinstaller

      - name: Build .exe with PyInstaller
        run: pyinstaller --onefile enviar_whats.py

      - name: Zip artifact
        run: powershell Compress-Archive -Path "dist/enviar_whats.exe" -DestinationPath dist/enviar_whats_bundle.zip

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/enviar_whats.exe,dist/enviar_whats_bundle.zip
          tag: ${{ github.ref_name }}
          generateReleaseNotes: true
