name: Build and Release EXE

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build EXE with PyInstaller
        run: pyinstaller --onefile enviar_whats.py

      - name: Create ZIP bundle
        run: |
          powershell Compress-Archive -Path "dist/enviar_whats.exe", "README.md" -DestinationPath dist/enviar_whats_bundle.zip

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/enviar_whats.exe,dist/enviar_whats_bundle.zip"
          tag: ${{ github.ref_name }}
          generateReleaseNotes: true
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
