name: Build Windows EXE

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt pyinstaller

    - name: Build EXE with PyInstaller
      run: pyinstaller --onefile enviar_whats.py

    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/enviar_whats.exe"
        tag: ${{ github.ref_name }}
        generateReleaseNotes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

