name: Build EXE and Upload Artifact

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt pyinstaller

      - name: Build .exe with PyInstaller
        run: pyinstaller --onefile enviar_whats.py

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v4
        with:
          name: enviar_whats_exe
          path: dist/enviar_whats.exe
